package:
  name: anguilla
  version: 0.0.1

source:
  path: ../..

build:
  skip: true  # [not x86_64 or py<36]
  number: 0

requirements:
  build:
    - clang >=11             # [linux]
    - clangxx >=11           # [linux]
    - gxx_linux-64           # [linux]
    - libcxx >=11            # [linux]
    - {{ compiler('cxx') }}  # [not linux]

  host:
    - python
    - pybind11 >=2.6.0
    - pip
    - scikit-build
    - cmake >=3.18
    - ninja

  run:
    - python
    - numpy
    - dataclasses                                    # [py==36]
    - libcxx >=11                                    # [linux]
    - {{ pin_compatible('libcxx', max_pin='x.x') }}  # [linux]

test:
  requires:
    - pytest
  imports:
    - anguilla
    - anguilla.hypervolume
  source_files:
    - tests/
  commands:
    - pytest tests

about:
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE.txt
  summary: A MO-CMA-ES implementation.
