version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: sphinx
    versions:
    - 3.5.0
    - 3.5.1
    - 3.5.2
  - dependency-name: sphinxcontrib-bibtex
    versions:
    - 2.1.4
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
