# Based on: https://github.com/pybind/scikit_build_example/blob/master/.github/workflows/conda.yml
# See also: https://github.com/marketplace/actions/setup-miniconda
# Detailed info. on options here: https://github.com/conda-incubator/setup-miniconda/blob/master/action.yml
name: Conda

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
    tags:
      - v*

jobs:
  build_packages:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8"]

    runs-on: ${{ matrix.platform }}

    defaults:
      run:
        shell: "bash -l {0}"

    env:
      CONDA_BUILD_PATH: "/tmp/conda-bld"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: *
          use-mamba: true
          channels: conda-forge
          auto-activate-base: true

      - name: Install build packages
        run: conda install conda-build conda-verify anaconda-client

      - name: Set up build directory
        run: mkdir -p ${CONDA_BUILD_PATH}

      - name: Build
        run: conda build conda-recipes/anguilla --output-folder ${CONDA_BUILD_PATH}

      - name: Install
        run: conda install -c ${CONDA_BUILD_PATH} anguilla

      - name: Test
        run: |
          conda install pytest
          pytest tests --import-mode=append --color=yes

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.CONDA_BUILD_PATH }}/**/*.tar.bz2

  # Upload to Anaconda.org (until recipe is submitted to Conda-Forge).
  upload_anaconda:
    needs: [build_packages]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
      - name: Upload packages
        run: anaconda -v -t ${{ secrets.ANACONDA_TOKEN }} upload dist/*.tar.bz2
