# Based on: https://github.com/pybind/scikit_build_example/blob/master/.github/workflows/pip.yml
name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  make_dist:
    name: Make distributions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: pybind/pybind11
    - uses: actions/setup-python@v2

    - name: Download requirements
      run: python -m pip install build

    - name: Build files
      run: |
        python -m build
        CMAKE_TOOLCHAIN_FILE=cmake/toolchains/cxx17.cmake PYBIND11_GLOBAL_SDIST=ON python -m build

    #- uses: actions/upload-artifact@v2
    #  with:
    #    path: dist/*

  build:
    name: Build with Pip
    needs: [make_dist]
    strategy:
      fail-fast: true
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.6", "3.8"]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    #- uses: actions/download-artifact@v2
    #  with:
    #    name: artifact
        path: dist

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools

    # See: https://github.com/microsoft/setup-msbuild
    - name: Prepare compiler environment for Windows
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build and install
      run: pip install --verbose . --find-links ${{ github.workspace }}/dist

    - name: Test
      run: |
        pip install pytest
        pytest tests


