# Based on: https://github.com/pybind/scikit_build_example/blob/master/.github/workflows/conda.yml
name: Conda

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
    tags:
      - v*

jobs:
  build_packages:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.6", "3.8"]
    runs-on: ${{ matrix.platform }}

    defaults:
      run:
        shell: "bash -l {0}"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get conda
        # See: https://github.com/conda-incubator/setup-miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          channels: conda-forge

      - name: Prepare
        run: conda install conda-build conda-verify anaconda-client

      - name: Build
        run: conda build conda-recipes/anguilla --output-folder .

      - name: Install
        run: conda install -c . anguilla

      - name: Test
        run: |
          conda install pytest
          pytest tests --import-mode=append --color=yes --ignore-glob=test_mocma.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./**/*.tar.bz2

  # Upload to Anaconda.org (until recipe is submitted to Conda-Forge).
  upload_anaconda:
    needs: [build_packages]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
      - name: Upload packages
        run: anaconda -v -t ${{ secrets.ANACONDA_TOKEN }} upload dist/*.tar.bz2
